### ISSUE TITLE
Implement wishlists functionality

### ISSUE THREAD

**Issue by ksavosteev** [VirtoCommerce-archieve/vc-module-wishlist#5]

**Comment by Woland2k** [comment]
@ksavosteev why is wishlist functionality is something separate from the shopping cart? We don't need to have different API from the shopping cart for wish list, they have exact same requirements as shopping carts. So in this case named shopping cart is a wish list. Wish list also can include predefined addresses, shipping etc especially in B2B scenario.

**Comment by asvishnyakov** [comment]
@Woland2k Just no. Wishlist hasn't large part of cart functionality like pricing, tax, shipping calculation. We just need a "lists" feature for our client project and will use these lists in 3 places. We don't need and don't want to use shopping cart for them.

---

UPD. And this task assigned to @ksavosteev

**Comment by Woland2k** [comment]
@asvishnyakov we do need functionality like pricing, tax and shipping for wishlists, especially in b2b scenarios. Functionality would be identical to shopping cart (convert wishlist to cart etc). So there is no need to create that functionality twice especially since cart does offer support for this already.
